### ISSUE TITLE
Can not run the demo.

### ISSUE THREAD

**Issue by mingqizhang** [Jiangfeng-Xiong/SiamRPN-TF#3]
There's no model_config.json.
No such file or directory: 'Logs/SiamRPN/track_model_checkpoints\\model_config.json'

**Comment by Jiangfeng-Xiong** [comment]
I didn't provide the pretrain model. You should use the [train script](https://github.com/Jiangfeng-Xiong/SiamRPN-TF/blob/master/train_SiamRPN.py) to get the trained model and config, which will be saved in folder `'Logs/SiamRPN`
