### ISSUE TITLE
about siamrpn++

### ISSUE THREAD

**Issue by huhu5036** [Jiangfeng-Xiong/SiamRPN-TF#5]
Hi,  your siamRPN is really great,  I do have a good tracking performance with your code.   However, I wonder whether you will update it to siamrpn++ or not.   I am looking forward to  your continuing progress.  Thank you very much.!

**Comment by Jiangfeng-Xiong** [comment]
Thank you for your compliments. This implementation of SiamRPN was done when I was still a master student， but my job now is not related to object tracking any more, so it will not be update to siamrpn++.
